name: Deploy Portafolio

on:
  workflow_run:
    workflows: ["Tests"]
    types: [completed]
    branches: [main]

permissions:
  contents: read

concurrency:
  group: portafolio-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy a Vercel
    runs-on: ubuntu-latest
    # Solo si el workflow "Tests" terminó en success
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout del commit que pasó Tests
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Vercel pull
        run: vercel pull --yes --environment=production --token="${{ env.VERCEL_TOKEN }}"

      - name: Vercel build
        run: vercel build --prod --token="${{ env.VERCEL_TOKEN }}"

      - name: Vercel deploy (prebuilt)
        run: vercel deploy --prebuilt --prod --token="${{ env.VERCEL_TOKEN }}"

