name: Test Portafolio
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Build app (Vite)
        run: npm run build

      - name: Instalar navegadores Playwright
        run: npx playwright install --with-deps

      - name: Correr tests E2E
        run: npx playwright test

      - name: Subir HTML con los resultados
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: test-results/playwright-report.html 
          retention-days: 7
